### ISSUE TITLE
Unable to build production website

### ISSUE THREAD

**Issue by jmurth1234** [UWPCommunity/uwpcommunity.github.io#83]
Getting this error when building the production bundle / react snap pages:

```
🔥  error at /projects: Error: Page crashed!
    at Page._onTargetCrashed (/home/ryan/Personal/uwpcommunity.github.io/node_modules/puppeteer/lib/Page.js:215:24)
    at CDPSession.<anonymous> (/home/ryan/Personal/uwpcommunity.github.io/node_modules/puppeteer/lib/Page.js:123:56)
    at CDPSession.emit (events.js:321:20)
    at CDPSession._onMessage (/home/ryan/Personal/uwpcommunity.github.io/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/home/ryan/Personal/uwpcommunity.github.io/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocket.<anonymous> (/home/ryan/Personal/uwpcommunity.github.io/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/home/ryan/Personal/uwpcommunity.github.io/node_modules/puppeteer/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:321:20)
    at Receiver.receiverOnMessage (/home/ryan/Personal/uwpcommunity.github.io/node_modules/puppeteer/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:321:20)
```

**Comment by jmurth1234** [comment]
Seemed to have just been an issue on my linux install

¯\\\_(ツ)_/¯
